# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://getfishie.com
title: GetFishie
email: jef@fuzzitail.com
author: Jef Armstrong
description: Fishing iPhone App Camera Bass Largemouth Log 
copyright: 'Copyright &copy; 2016 Jef Armstrong. All Rights Reserved.'
credits: 'Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
exclude: 
    - Guardfile
    - Gemfile
    - Gemfile.lock
    - README.md
    - assets

include:
    - ios
    - audio

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/getfishie
  - title: instagram
    url: https://www.instagram.com/getfishie/
  